_target_: src.models.model.PoseConditional
u_net:
  _target_: src.models.u_net.denoising_diffusion_pytorch.u_net.UNet
  u_net_dim: 192
  rot_representation_dim: 6
  pose_mlp_name: "single_layer"
  encoder:
    _target_: src.models.encoder.AutoencoderKL.VAE_StableDiffusion
    pretrained_path: ${machine.root_dir}/pretrained/stable-diffusion-v1-5_vae.pth
    latent_dim: 4
    name: VAE
  
  pretrained_path: 

save_dir: ${save_dir}

optim_config:
  loss_type: l1
  lr: 5e-5
  weight_decay: 0.0005
  warm_up_steps: 500
  use_inv_deltaR: true
  
testing_config:
  similarity_metric: l2 # cosine

checkpoint_path: